
log_dir: ./logs/train/${now:%Y-%m-%d}/${now:%H-%M-%S}  

model:
  backbone:
    type: cnn  # Options: "cnn", "vit"
    name: resnet50  # For CNN: "resnet18", "resnet34", etc; For ViT: "swin_tiny", "swin_small", etc
    out_features: ['c2', 'c3', 'c4', 'c5']  

  proj_hidden_dim: 2048
  proj_output_dim: 2048
  use_projector: true

data:
  dataset_path: /path/to/dataset
  batch_size: 64
  num_workers: 12 
  size: [224, 224]  
  num_crops: 2
  use_labels: true
  
training:
  epoch: 300
  optim:
    lr: 0.3
    weight_decay: 1e-4
    warmup_epochs: 10
    epoch: ${training.epoch}
    min_lr: 1e-6
    warmup_start_lr: 3.0e-5
  
  loss:
    std_coeff: 1.0
    cov_coeff: 80.0


hydra:
  run:
    dir: ./outputs/train_jepa/${now:%Y-%m-%d}/${now:%H-%M-%S}